version: '3'

services:
    redis:
        image: redis
        ports:
            - 6379:6379
    frontend:
        image: frontend
        ports:
            - 5000:5000
    backend:
        image: backend
        ports:
            - 8000:8000
        environment:
            - REDIS=redis
            - DB_USERNAME=postgres
            - DB_PASSWORD=example
            - DB_HOST=db
        depends_on:
            - db
    db:
        image: postgres
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: example
