FROM ubuntu:16.04

RUN apt-get update && apt-get install -y curl && \
    curl -sL https://deb.nodesource.com/setup_10.x | bash - && \
    apt-get update && apt-get install -y nodejs && \
    rm -rf /var/lib/apt/lists/* 

WORKDIR /app
COPY . .
RUN npm install
EXPOSE 8000

ENTRYPOINT ["npm", "run", "start"]
