version: '3'

services:
    backend:
        image: frontend
        ports:
            - 5000:5000
    frontend:
        image: backend
        ports:
            - 8000:8000
        volumes:
            - ./logs.txt:/app/logs.txt
