version: '3'

services:
    frontend:
        image: frontend
        environment:
            - API_URL=http://localhost:8000
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
        depends_on:
            - backend
    redis:
        image: redis
        ports:
            - 6379:6379
    backend:
        image: backend
        ports:
            - 8000:8000
        environment:
            - REDIS=redis
            - FRONT_URL=http://localhost
            - DB_USERNAME=postgres
            - DB_PASSWORD=example
            - DB_HOST=db
        depends_on:
            - redis
            - db
    db:
        image: postgres
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: example
        volumes:
            - ./data:/var/lib/postgresql/data
